### ISSUE TITLE
When to use `package X_test`

### ISSUE THREAD

**Issue by ebuchman** [tendermint/coding#4]
`package X_test` forces you to do testing through the public interface. Most of our packages dont use it. When should they ?

**Comment by ethanfrey** [comment]
I think it is a good practice in general, when enough of the functionality is exposed to test decently. It has forced me a number of times to modify the API, as some interesting functionality was only possible through private methods (even if only needed for test setup, very good to be able to set up tests in other packages).

I don't use it sometimes when there is lots of logic in private methods and it is not practical to test without it.  Or out of laziness. But I think it is usually good practice.

**Comment by zramsay** [comment]
cc @odeke-em

**Comment by odeke-em** [comment]
Thanks for the tag @zramsay!

Personally I prefer this style of X_test because as everyone has noted, it makes us test code through the public API. 2 other advantages:
- It also helps with making sure that the APIs and helpers are more mature since we can't be modifying helpers in the code files while using this style.
- It helps in isolating simple reproductions for bugs in terms of failing tests for example https://github.com/tendermint/tmlibs/issues/36 which was isolated directly from https://github.com/tendermint/merkleeyes/pull/40.

With that being said, however, the comfort of the developer(Developer Experience) wins IMHO. We can slowly start adopting the style if everyone thinks it has more merit.

**Comment by zramsay** [comment]
see #46

**Comment by jaekwon** [comment]
Often you need to call internal functions because to expose certain functions is bad.  We should take care to expose only those functions that need to be exposed, so it becomes necessary to keep certain tests internal.

Use external packages for integration testing.
