### ISSUE TITLE
new name for make get_vendor_deps

### ISSUE THREAD

**Issue by rigelrozanski** [tendermint/coding#57]
I noticed that it's pretty annoying to type these words, I also noticed that there doesn't seem to be a whole lot of standardization of using the keywords `get_vendor_deps` - I think this is why back we were using `glide` I (and many others) would type `glide install` as opposed to `make get_vendor_deps` <- it's just much easier to type without underscores... I notice now people are using `dep ensure` (@ebuchman) sometimes instead now too... so yeah I propose we use something new and fast to type such as:

`make dep`
`make deps`
`make ensure`
`make ensuredeps`

These can even be in complement to `make get_vendor_deps` if we really want to maintain that

**Comment by greg-szabo** [comment]
I'm wholeheartedly behind this initiative provided two conditions are met:
1. We agree on a naming convention and we agree stick to it for the 6 months. (at least)
2. We update all repos involved (cosmos-sdk, tendermint, ethermint at least) all at once.

The reason for the above is that in some cases I'm already using `get_vendor_deps` in automation and this will break things. Also, I'd like to make automation compatible with all our repositories so we don't have to redo everything for each of them.

Additional thoughts:
Maybe we could standardize more Makefile targets across repos. `get_tools`, `get_vendor_deps`, `build` seem to be almost there, but for example cosmos-sdk uses `install` instead of `build`.

**Comment by zramsay** [comment]
lets not change this, lest we break docs

**Comment by rigelrozanski** [comment]
I disagree, I think it's a hassle to type - we should not get lazy about making constructive time saving updates to our tooling just because we need to update docs in the process - we should make updating docs for stuff like this easy

**Comment by zramsay** [comment]
hassle to type? make targets autocomplete using the `tab` key. have any users of our stack reported trouble/confusing/difficulty because `make get_vendor_deps` is too long to type? feel free to re-open if you want to take full responsibility for updating the docs if/when this change is implemented.

**Comment by rigelrozanski** [comment]
Not always so easy, depending on OS haven't been able to get working on my mac. 
https://stackoverflow.com/questions/33760647/makefile-autocompletion-on-mac

When you're typing this command relentlessly it becomes a hassle to use underscores - Also I know many people who type `dep ensure` because it's faster - this becomes a problem if we ever want to upgrade our dep process (as we have done to a custom version of glide in the past). So yeah I mean, I do want to this, among other Makefile convention improvement - so yes I think this is an important change for Tendermint, please do not close again

**Comment by rigelrozanski** [comment]
Before we implement this - let's make updating docs due to cross-repo breaking changes an easier task - this shouldn't be a complicated change that takes many hours to update.

**Comment by zramsay** [comment]
implemented in various forms in various repos
